"""
alerts.py — Alert management system for IPC Debugger.

Manages alerts generated by the analysis engine with severity levels,
cooldowns, and alert history.

Interface:
    AlertManager.add_alert(severity, alert_type, message)  → Alert
    AlertManager.get_alerts(severity)                       → list[Alert]
    AlertManager.clear()                                    → None
"""

import time
import threading
from dataclasses import dataclass, field
from typing import List, Optional, Dict


@dataclass
class Alert:
    """A single alert generated by the analysis engine."""
    severity: str        # INFO / WARNING / CRITICAL
    alert_type: str      # DEADLOCK / BOTTLENECK / LATENCY / FLOOD / RACE
    message: str
    timestamp: float = field(default_factory=time.time)

    def __str__(self):
        return f"[{self.severity}] {self.alert_type}: {self.message}"


class AlertManager:
    """
    Manages alerts with severity levels and cooldown periods.
    Prevents duplicate alerts from spamming the GUI.
    """

    SEVERITY_LEVELS = ["INFO", "WARNING", "CRITICAL"]

    def __init__(self, cooldown_seconds: float = 5.0):
        self._alerts: List[Alert] = []
        self._cooldowns: Dict[str, float] = {}
        self._lock = threading.Lock()
        self.cooldown_seconds = cooldown_seconds

    def add_alert(self, severity: str,
                  alert_type: str, message: str) -> Optional[Alert]:
        """
        Add a new alert if cooldown has passed.
        Returns the alert or None if suppressed.
        """
        key = f"{alert_type}"
        now = time.time()

        with self._lock:
            # Check cooldown
            last = self._cooldowns.get(key, 0)
            if now - last < self.cooldown_seconds:
                return None

            alert = Alert(severity=severity,
                         alert_type=alert_type,
                         message=message)
            self._alerts.append(alert)
            self._cooldowns[key] = now
            return alert

    def get_alerts(self, severity: Optional[str] = None) -> List[Alert]:
        """Return all alerts, optionally filtered by severity."""
        with self._lock:
            if severity:
                return [a for a in self._alerts
                        if a.severity == severity]
            return list(self._alerts)

    def get_critical(self) -> List[Alert]:
        """Return only CRITICAL alerts."""
        return self.get_alerts("CRITICAL")

    def get_warnings(self) -> List[Alert]:
        """Return only WARNING alerts."""
        return self.get_alerts("WARNING")

    def get_latest(self, n: int = 10) -> List[Alert]:
        """Return the last n alerts."""
        with self._lock:
            return list(self._alerts[-n:])

    def count_by_severity(self) -> Dict[str, int]:
        """Return count of alerts per severity level."""
        with self._lock:
            return {
                s: sum(1 for a in self._alerts if a.severity == s)
                for s in self.SEVERITY_LEVELS
            }

    def clear(self) -> None:
        with self._lock:
            self._alerts.clear()
            self._cooldowns.clear()

    def __len__(self) -> int:
        return len(self._alerts)